# Generated by Django 4.2.6 on 2024-01-24 21:38

import accounts.validations.profile
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_otp_full_name_remove_otp_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name="otp",
            name="Full_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام کامل"
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(
                default=1, max_length=255, verbose_name="پست الکترونیک"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otp",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="UserImage", verbose_name="عکس کاربر"
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_doctor",
            field=models.BooleanField(default=False, verbose_name="پزشک"),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_patient",
            field=models.BooleanField(default=False, verbose_name="بیمار"),
        ),
        migrations.AddField(
            model_name="otp",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="نام کاربری",
            ),
        ),
        migrations.CreateModel(
            name="ProfilePatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=1000,
                        validators=[
                            accounts.validations.profile.validate_profile_title
                        ],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile/patient"
                    ),
                ),
                ("email", models.EmailField(max_length=1000, unique=True)),
                ("status", models.BooleanField(default=True)),
                ("bio", models.TextField(blank=True, max_length=100000, null=True)),
                ("heart_beat", models.SmallIntegerField(blank=True, null=True)),
                (
                    "body_water",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=3, null=True
                    ),
                ),
                (
                    "hemoglobin",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=3, null=True
                    ),
                ),
                (
                    "blood_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.bloodtype",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
